@echo off
echo Downloading Electron...
powershell -Command "& {Invoke-WebRequest -Uri 'https://github.com/electron/electron/releases/download/v28.0.0/electron-v28.0.0-win32-x64.zip' -OutFile 'electron.zip'}"
echo Extracting Electron...
powershell -Command "& {Expand-Archive -Path 'electron.zip' -DestinationPath '.' -Force}"
echo Starting Welding Parameter Manager...
electron.exe simple-main.js
pause 